package ping

// A shallow fork of the "golang.org/x/net/internal/iana" package

// Protocol Numbers, Updated: 2017-10-13
const (
	protocolIP             = 0   // IPv4 encapsulation, pseudo protocol number
	protocolHOPOPT         = 0   // IPv6 Hop-by-Hop Option
	protocolICMP           = 1   // Internet Control Message
	protocolIGMP           = 2   // Internet Group Management
	protocolGGP            = 3   // Gateway-to-Gateway
	protocolIPv4           = 4   // IPv4 encapsulation
	protocolST             = 5   // Stream
	protocolTCP            = 6   // Transmission Control
	protocolCBT            = 7   // CBT
	protocolEGP            = 8   // Exterior Gateway Protocol
	protocolIGP            = 9   // any private interior gateway (used by Cisco for their IGRP)
	protocolBBNRCCMON      = 10  // BBN RCC Monitoring
	protocolNVPII          = 11  // Network Voice Protocol
	protocolPUP            = 12  // PUP
	protocolEMCON          = 14  // EMCON
	protocolXNET           = 15  // Cross Net Debugger
	protocolCHAOS          = 16  // Chaos
	protocolUDP            = 17  // User Datagram
	protocolMUX            = 18  // Multiplexing
	protocolDCNMEAS        = 19  // DCN Measurement Subsystems
	protocolHMP            = 20  // Host Monitoring
	protocolPRM            = 21  // Packet Radio Measurement
	protocolXNSIDP         = 22  // XEROX NS IDP
	protocolTRUNK1         = 23  // Trunk-1
	protocolTRUNK2         = 24  // Trunk-2
	protocolLEAF1          = 25  // Leaf-1
	protocolLEAF2          = 26  // Leaf-2
	protocolRDP            = 27  // Reliable Data Protocol
	protocolIRTP           = 28  // Internet Reliable Transaction
	protocolISOTP4         = 29  // ISO Transport Protocol Class 4
	protocolNETBLT         = 30  // Bulk Data Transfer Protocol
	protocolMFENSP         = 31  // MFE Network Services Protocol
	protocolMERITINP       = 32  // MERIT Internodal Protocol
	protocolDCCP           = 33  // Datagram Congestion Control Protocol
	protocol3PC            = 34  // Third Party Connect Protocol
	protocolIDPR           = 35  // Inter-Domain Policy Routing Protocol
	protocolXTP            = 36  // XTP
	protocolDDP            = 37  // Datagram Delivery Protocol
	protocolIDPRCMTP       = 38  // IDPR Control Message Transport Proto
	protocolTPPP           = 39  // TP++ Transport Protocol
	protocolIL             = 40  // IL Transport Protocol
	protocolIPv6           = 41  // IPv6 encapsulation
	protocolSDRP           = 42  // Source Demand Routing Protocol
	protocolIPv6Route      = 43  // Routing Header for IPv6
	protocolIPv6Frag       = 44  // Fragment Header for IPv6
	protocolIDRP           = 45  // Inter-Domain Routing Protocol
	protocolRSVP           = 46  // Reservation Protocol
	protocolGRE            = 47  // Generic Routing Encapsulation
	protocolDSR            = 48  // Dynamic Source Routing Protocol
	protocolBNA            = 49  // BNA
	protocolESP            = 50  // Encap Security Payload
	protocolAH             = 51  // Authentication Header
	protocolINLSP          = 52  // Integrated Net Layer Security  TUBA
	protocolNARP           = 54  // NBMA Address Resolution Protocol
	protocolMOBILE         = 55  // IP Mobility
	protocolTLSP           = 56  // Transport Layer Security Protocol using Kryptonet key management
	protocolSKIP           = 57  // SKIP
	protocolIPv6ICMP       = 58  // ICMP for IPv6
	protocolIPv6NoNxt      = 59  // No Next Header for IPv6
	protocolIPv6Opts       = 60  // Destination Options for IPv6
	protocolCFTP           = 62  // CFTP
	protocolSATEXPAK       = 64  // SATNET and Backroom EXPAK
	protocolKRYPTOLAN      = 65  // Kryptolan
	protocolRVD            = 66  // MIT Remote Virtual Disk Protocol
	protocolIPPC           = 67  // Internet Pluribus Packet Core
	protocolSATMON         = 69  // SATNET Monitoring
	protocolVISA           = 70  // VISA Protocol
	protocolIPCV           = 71  // Internet Packet Core Utility
	protocolCPNX           = 72  // Computer Protocol Network Executive
	protocolCPHB           = 73  // Computer Protocol Heart Beat
	protocolWSN            = 74  // Wang Span Network
	protocolPVP            = 75  // Packet Video Protocol
	protocolBRSATMON       = 76  // Backroom SATNET Monitoring
	protocolSUNND          = 77  // SUN ND PROTOCOL-Temporary
	protocolWBMON          = 78  // WIDEBAND Monitoring
	protocolWBEXPAK        = 79  // WIDEBAND EXPAK
	protocolISOIP          = 80  // ISO Internet Protocol
	protocolVMTP           = 81  // VMTP
	protocolSECUREVMTP     = 82  // SECURE-VMTP
	protocolVINES          = 83  // VINES
	protocolTTP            = 84  // Transaction Transport Protocol
	protocolIPTM           = 84  // Internet Protocol Traffic Manager
	protocolNSFNETIGP      = 85  // NSFNET-IGP
	protocolDGP            = 86  // Dissimilar Gateway Protocol
	protocolTCF            = 87  // TCF
	protocolEIGRP          = 88  // EIGRP
	protocolOSPFIGP        = 89  // OSPFIGP
	protocolSpriteRPC      = 90  // Sprite RPC Protocol
	protocolLARP           = 91  // Locus Address Resolution Protocol
	protocolMTP            = 92  // Multicast Transport Protocol
	protocolAX25           = 93  // AX.25 Frames
	protocolIPIP           = 94  // IP-within-IP Encapsulation Protocol
	protocolSCCSP          = 96  // Semaphore Communications Sec. Pro.
	protocolETHERIP        = 97  // Ethernet-within-IP Encapsulation
	protocolENCAP          = 98  // Encapsulation Header
	protocolGMTP           = 100 // GMTP
	protocolIFMP           = 101 // Ipsilon Flow Management Protocol
	protocolPNNI           = 102 // PNNI over IP
	protocolPIM            = 103 // Protocol Independent Multicast
	protocolARIS           = 104 // ARIS
	protocolSCPS           = 105 // SCPS
	protocolQNX            = 106 // QNX
	protocolAN             = 107 // Active Networks
	protocolIPComp         = 108 // IP Payload Compression Protocol
	protocolSNP            = 109 // Sitara Networks Protocol
	protocolCompaqPeer     = 110 // Compaq Peer Protocol
	protocolIPXinIP        = 111 // IPX in IP
	protocolVRRP           = 112 // Virtual Router Redundancy Protocol
	protocolPGM            = 113 // PGM Reliable Transport Protocol
	protocolL2TP           = 115 // Layer Two Tunneling Protocol
	protocolDDX            = 116 // D-II Data Exchange (DDX)
	protocolIATP           = 117 // Interactive Agent Transfer Protocol
	protocolSTP            = 118 // Schedule Transfer Protocol
	protocolSRP            = 119 // SpectraLink Radio Protocol
	protocolUTI            = 120 // UTI
	protocolSMP            = 121 // Simple Message Protocol
	protocolPTP            = 123 // Performance Transparency Protocol
	protocolISIS           = 124 // ISIS over IPv4
	protocolFIRE           = 125 // FIRE
	protocolCRTP           = 126 // Combat Radio Transport Protocol
	protocolCRUDP          = 127 // Combat Radio User Datagram
	protocolSSCOPMCE       = 128 // SSCOPMCE
	protocolIPLT           = 129 // IPLT
	protocolSPS            = 130 // Secure Packet Shield
	protocolPIPE           = 131 // Private IP Encapsulation within IP
	protocolSCTP           = 132 // Stream Control Transmission Protocol
	protocolFC             = 133 // Fibre Channel
	protocolRSVPE2EIGNORE  = 134 // RSVP-E2E-IGNORE
	protocolMobilityHeader = 135 // Mobility Header
	protocolUDPLite        = 136 // UDPLite
	protocolMPLSinIP       = 137 // MPLS-in-IP
	protocolMANET          = 138 // MANET Protocols
	protocolHIP            = 139 // Host Identity Protocol
	protocolShim6          = 140 // Shim6 Protocol
	protocolWESP           = 141 // Wrapped Encapsulating Security Payload
	protocolROHC           = 142 // Robust Header Compression
	protocolReserved       = 255 // Reserved
)
