name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23.2'

    - name: Build
      run: ./build.sh

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.23.2'

    - name: Test
      run: go test -race ./...

  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.23.2'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          verify: false
          # This linter works based on the file modification when running under github actions because it's
          # not allowed access to the git history and therefore gets the wrong date for all files.
          args: --disable goheader